# Generated by Django 4.1.1 on 2022-09-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todolistitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
